#!/usr/bin/env bash
# attempt10: cleaned-up code. 16 B find-queue entries are the default (where exact); DEEP_VECTORIZATION
# = 4-entry block pop/push. Plus two configurations that must fall back to the 32 B entry (compile check).
set -e
cd "$(dirname "$0")"
COMMON="-DCMAKE_BUILD_TYPE=RelWithDebInfo -DBRANCH=simd -DBUCKETIZATION=ON -DCAS_FAST_PATH=ON -DCAS_PREFETCH_INSERTION=DOUBLE -DPREFETCH=DOUBLE -DCAS_FIND_RING_OFFSETS=ON -DCAS_FIND_COMPRESS_VALUE=ON -DCAS_FIND_KSHIFT=ON -DUNIFORM_PROBING=ON -DREAD_BEFORE_CAS=ON -DCPUFREQ_MHZ=2700 -DKEY_LEN=8 -DKMER_LEN=8 -DBENCHMARK_BACKEND=NONE -DCAS_FIND_EMBCAST=OFF"
declare -A EXTRA=(
  [q16]="-DHASHER=crc -DDRAMHiT_VARIANT=2025_INLINE -DDEEP_VECTORIZATION=OFF"
  [deepvec]="-DHASHER=crc -DDRAMHiT_VARIANT=2025_INLINE -DDEEP_VECTORIZATION=ON"
  [pf8]="-DHASHER=crc -DDRAMHiT_VARIANT=2025_INLINE -DDEEP_VECTORIZATION=ON -DFIND_PF_DIST=8"
  [pf16]="-DHASHER=crc -DDRAMHiT_VARIANT=2025_INLINE -DDEEP_VECTORIZATION=ON -DFIND_PF_DIST=16"
  [pf24]="-DHASHER=crc -DDRAMHiT_VARIANT=2025_INLINE -DDEEP_VECTORIZATION=ON -DFIND_PF_DIST=24"
  [pf32]="-DHASHER=crc -DDRAMHiT_VARIANT=2025_INLINE -DDEEP_VECTORIZATION=ON -DFIND_PF_DIST=32"
  [dc24]="-DHASHER=crc -DDRAMHiT_VARIANT=2025_INLINE -DDEEP_VECTORIZATION=ON -DFIND_PF_DIST=24 -DSPLIT_ARGS=OFF"
  [qc]="-DHASHER=crc -DDRAMHiT_VARIANT=2025_INLINE -DDEEP_VECTORIZATION=OFF -DFIND_PF_DIST= -DSPLIT_ARGS=OFF"
  [dc24s]="-DHASHER=crc -DDRAMHiT_VARIANT=2025_INLINE -DDEEP_VECTORIZATION=ON -DFIND_PF_DIST=24 -DSPLIT_ARGS=ON"
  [qcs]="-DHASHER=crc -DDRAMHiT_VARIANT=2025_INLINE -DDEEP_VECTORIZATION=OFF -DFIND_PF_DIST= -DSPLIT_ARGS=ON"
  [chk_city]="-DHASHER=city -DDRAMHiT_VARIANT=2025_INLINE -DDEEP_VECTORIZATION=OFF"
  [chk_2023]="-DHASHER=crc -DDRAMHiT_VARIANT=2023 -DDEEP_VECTORIZATION=OFF"
)
for v in ${@:-q16 deepvec chk_city chk_2023}; do
  mkdir -p $v/build
  (cd $v/build && cmake ../../../../../.. $COMMON ${EXTRA[$v]} > cmake.log 2>&1 && \
     { make -j24 dramhit > make.log 2>&1 || { grep -m3 -A8 "error" make.log; exit 1; }; })
  cp $v/build/dramhit $v/dramhit
  echo "$v $(md5sum $v/dramhit | cut -d' ' -f1)"
done
